[package]
name = "inner-shelter-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = "0.3"
redis = { version = "0.23", features = ["tokio-comp", "aio"] }
uuid = { version = "1", features = ["v4"] }