[package]
name = "inner-shelter-server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
redis = { version = "0.23", features = ["aio", "tokio-comp"] }  # Add "tokio-comp" feature
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }  # Enable v4 for UUID generation
jsonwebtoken = "7"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"